version: "2.1"
services:
  prometheus:
    build: prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "1338:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "1337:3000"

  fake-prometheus-data:
    image: grafana/fake-data-gen
    environment:
      FD_DATASOURCE: prom

  prometheus-random-data:
    build: prometheus_random_data

